### PR TITLE
[0.1.1] - Explicitly subclass chef/handler

### PR DESCRIPTION
**Pull request by jdinthe**
Just for aesthetics, mostly.

### CODE REVIEW

**Comment by whilp** [comment]
+1

**Comment by whilp** [comment]
Also, FYI, stuff like this is way easier to review without whitespace:

https://github.com/SimpleFinance/chef-handler-sensu-event/pull/2/files?w=1

**Comment by jdinthe** [comment]
Whitespace diff is done by Github, so I can't really control that, unless there's a way to do w=1 by default?

**Comment by whilp** [comment]
No, you can't control it -- I'm just saying that it's a handy tool for cases like this.

**Comment by jdinthe** [comment]
Word, will remember. At least that's easy to add.

**Pull request merged**
